### ISSUE TITLE
Example broken, installation document broken

### ISSUE THREAD

**Issue by anhtuank7c** [mrousavy/react-native-jsi-contacts#4]
- [ ] Refer link to react-native-mmkv to setup JSIModulePackage's broken
- [ ] Could not found JSIContacts module on iOS
- [ ] example broken
![image](https://user-images.githubusercontent.com/3163410/151646143-2254ba76-506e-48f2-803d-b23ad5d767ae.png)

**Comment by mrousavy** [comment]
It literally says on the first page in the README that iOS is not implemented.

![Screenshot 2022-01-31 at 09 40 06](https://user-images.githubusercontent.com/15199031/151762730-326a4e3a-5576-4b77-85be-9267772aa9e5.png)

Also, the Example is not "broken", you are using it on iOS, which is not implemented. Read before posting an issue.

**Comment by mrousavy** [comment]
But yes, I agree that the guide from MMKV is gone now. I found a clever solution to autoinstall MMKV without the user having to edit native files, I could probably also implement that for JSI Contacts

**Comment by anhtuank7c** [comment]
Thanks @mrousavy
